steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/sleepr-436409/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-southeast1-docker.pkg.dev/sleepr-436409/reservations/production']
  # auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/sleepr-436409/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-southeast1-docker.pkg.dev/sleepr-436409/auth/production']
  # notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/sleepr-436409/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-southeast1-docker.pkg.dev/sleepr-436409/notifications/production']
  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast1-docker.pkg.dev/sleepr-436409/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'asia-southeast1-docker.pkg.dev/sleepr-436409/payments/production']

options:
  logging: CLOUD_LOGGING_ONLY